### PR TITLE
Made hero images responsive

### LINKED ISSUE #18: Hero carousel is not fully responsive
This could be fixed by using divs with background images instead.
screen shot 2016-04-19 at 11 01 21 pm

### PR DESCRIPTION
**Pull request by darindimitroff**
Replaced images with divs with background-images. Should fix #18.

### CODE REVIEW

**Comment by imcatnoone** [comment]
Hey @darindimitroff thanks so much for taking the time on this. Did you check on a variety of screen sizes to ensure this works and didn’t break the crossfading image JS in any way? Want to make sure before I go ahead and merge.

**Comment by darindimitroff** [comment]
It shouldn't break any of the existing behavior. Looks okay on all screens I tested on, here are a few comparisons.

ipadmini-original
ipadmini-updated
iphone6-original
iphone6-updated

In a perfect scenario, the hero container's height would also be responsive in relation to the viewport height, but that might require changes to other components too.

**Comment by imcatnoone** [comment]
All works great. Seems to be a few wonky things happening on iPhone 5S but that is not an issue at all. Fixing that up this week. Thank you so much, @darindimitroff! 🎉

**Comment by darindimitroff** [comment]
I saw it yesterday in 4s and 5s widths, if I remember correctly the input element is too wide because of the hard-coded right padding. I would have fixed it too, but didn't want to interfere with your design, there are many ways to "fix" it based on the layout you're trying to achieve.

**Pull request merged**
